library(Microsoft365R)
outl <- get_personal_outlook()

# compose an email with blastula
library(blastula)
bl_body <- "## Hello!

This is an email message that was generated by the blastula package.

We can use **Markdown** formatting with the `md()` function.

Cheers,

The blastula team"

bl_em <- compose_email(
  body=md(bl_body),
  footer=md("sent via Microsoft365R")
)
em <- outl$create_email(bl_em, subject="Hello from R", to="duquedsealand@gmail.com")

# add an attachment and send it
em$add_attachment(".gitignore")
em$send()

# list the most recent emails in your inbox
emlst <- outl$list_emails()

# reply to the most recent email
# emlst[[1]]$
#   create_reply("Replying from R")$
#   send()